import "./globals.css";
import { Manrope, Archivo } from "next/font/google";

// If loading a variable font, you don't need to specify the font weight
const manrope = Manrope({ subsets: ["latin"], display: "swap" });
const archivo = Archivo({ subsets: ["latin"], display: "swap" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${manrope.className} text-white-100 bg-black-100`}>
        {children}
      </body>
    </html>
  );
}
